### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by nakai-omer** [nvidia-isaac/nvblox#12]
Hello,

We are building a docker image on top of this image: `dustynv/ros:humble-ros-base-l4t-r35.1.0` for a Jetson Xavier NX. 

When we run:
```
RUN source ${ROS_ROOT}/install/setup.bash && \
    colcon build 
```
We get the following error:
```
 > [ 8/10] RUN source /opt/ros/humble/install/setup.bash && colcon build:
#13 33.64 CMake Error at CMakeLists.txt:135 (set_target_properties):
#13 33.64   set_target_properties called with incorrect number of arguments.
#13 33.64 
#13 33.64 
#13 33.64 ---
#13 33.64 Failed   <<< nvblox [27.8s, exited with code 1]
```
Line 135 is:
```
   set_target_properties(nvblox_lib PROPERTIES CUDA_ARCHITECTURES ${CMAKE_CUDA_ARCHITECTURES})
```

We have narrowed it down to CMAKE_CUDA_ARCHITECTURES not being set. 
If we create an image without running `colcon build`, then running the image on the Jetson and manually running `colcon build`, it works fine, and we can also see CMAKE_CUDA_ARCHITECTURES is set. 

Also building this package on our development computer works fine. Just running a docker build fails. 

We are presuming this might be related to what the docs about [CMAKE_CUDA_ARCHITECTURES]:(https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_ARCHITECTURES.html) state
```
Users are encouraged to override this, as the default varies across compilers and compiler versions.
``` 

We are building the docker image on an x86_64 cpu, but for an arm64 cpu by declaring the platform via docker-compose.yaml:
```
version: "3.9"
services:
  nakai-robot:
    privileged: true
    network_mode: "host"
    platform: linux/arm64/v8
    container_name: nakai-robot
    image: nakairobotics/nakai:nakai
    ...
 ```
